# -*- coding: utf-8 -*-
"""scholarPro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x7zY6RMFzUgsYMzuYCUe0CkLmgBPXL2p
"""

!pip install -q gradio arxiv semanticscholar aiohttp feedparser groq
import gradio as gr
import asyncio
import aiohttp
import pandas as pd
import sqlite3
import os
import urllib.parse
import feedparser
from groq import Groq

from google.colab import userdata

# --- SECURITY: API KEY CONFIGURATION ---
try:
    # Use the userdata module for reliable secret retrieval
    GROQ_KEY = userdata.get('scholarApi')
    SS_API_KEY = userdata.get('scholar_api_key')
except Exception:
    GROQ_KEY = None
    SS_API_KEY = None

try:
    if GROQ_KEY:
        GROQ_CLIENT = Groq(api_key=GROQ_KEY)
        print("✅ Groq Client initialized successfully.")
    else:
        GROQ_CLIENT = None
        print("⚠️ Warning: 'scholarApi' key not found.")
except Exception as e:
    print(f"❌ Initialization Error: {e}")
    GROQ_CLIENT = None
# --- DATABASE SETUP ---
DB_PATH = "scholarstream_pro.db"
def init_db():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute('''CREATE TABLE IF NOT EXISTS saved_papers
                     (id INTEGER PRIMARY KEY, title TEXT, authors TEXT, year TEXT, abstract TEXT, url TEXT)''')
init_db()

# --- RESEARCH ENGINES (OpenAlex + ArXiv Fallback) ---
async def fetch_real_data(query):
    encoded_query = urllib.parse.quote(query)

    # 1. PRIMARY: OpenAlex (No key required, high reliability)
    openalex_url = f"https://api.openalex.org/works?search={encoded_query}&limit=10"
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(openalex_url, timeout=8) as response:
                if response.status == 200:
                    data = await response.json()
                    results = []
                    for item in data.get('results', []):
                        results.append({
                            "Title": item.get('display_name', 'Untitled'),
                            "Authors": ", ".join(a.get('author', {}).get('display_name', '') for a in item.get('authorships', [])[:3]),
                            "Year": str(item.get('publication_year', 'N/A')),
                            "Abstract": "Detailed context available for AI analysis." if item.get('abstract_inverted_index') else "No abstract provided.",
                            "URL": item.get('doi') or item.get('id'),
                            "Citations": f"{item.get('cited_by_count', 0)} (OpenAlex)"
                        })
                    if results: return pd.DataFrame(results)
    except:
        pass

    # 2. FALLBACK: ArXiv
    arxiv_url = f"http://export.arxiv.org/api/query?search_query=all:{encoded_query}&max_results=10"
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(arxiv_url, timeout=10) as resp:
                feed = feedparser.parse(await resp.text())
                results = []
                for entry in feed.entries:
                    results.append({
                        "Title": entry.title.replace('\n', ' ').strip(),
                        "Authors": ", ".join(a.name for a in entry.authors) if hasattr(entry, 'authors') else "Unknown",
                        "Year": entry.published[:4] if hasattr(entry, 'published') else "N/A",
                        "Abstract": entry.summary.replace('\n', ' ').strip(),
                        "URL": entry.link,
                        "Citations": "N/A (ArXiv)"
                    })
                return pd.DataFrame(results)
    except Exception:
        return pd.DataFrame([{"Title": "No results found.", "Authors": "-", "Year": "-", "Citations": "-"}])

# --- RAG CHAT LOGIC (Updated Model) ---
def run_ai_chat(question, paper_data):
    if not GROQ_CLIENT: return "⚠️ AI Error: 'scholarApi' API key missing in Secrets."
    if not paper_data or 'Abstract' not in paper_data: return "⚠️ Please select a paper from results first!"

    context = paper_data.get('Abstract', "No context available.")
    prompt = f"Context: {context}\n\nQuestion: {question}\n\nAnalyze the context and answer the question precisely:"

    try:
        # Using the recommended Llama-3.1 replacement model
        completion = GROQ_CLIENT.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "system", "content": "You are a professional research assistant."},
                      {"role": "user", "content": prompt}],
            temperature=0.1
        )
        return completion.choices[0].message.content
    except Exception as e:
        return f"AI Error: {str(e)}"

# --- UI REFRESH LOGIC ---
def save_and_refresh(paper_data):
    if not paper_data or 'Title' not in paper_data: return "⚠️ Selection required!", None
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("INSERT INTO saved_papers (title, authors, year, abstract, url) VALUES (?,?,?,?,?)",
                  (paper_data['Title'], paper_data['Authors'], paper_data['Year'], paper_data['Abstract'], paper_data['URL']))
    new_lib = pd.read_sql_query("SELECT id, title, year FROM saved_papers", sqlite3.connect(DB_PATH))
    return "✅ Saved to Personal Library!", new_lib

# --- GRADIO INTERFACE ---
with gr.Blocks(theme=gr.themes.Soft(primary_hue="slate", secondary_hue="amber")) as demo:
    selected_paper_state = gr.State({})

    gr.Markdown("# 🏛️ SCHOLAR STREAM PRO")
    gr.Markdown("*Authenticated High-Speed Research & RAG Engine*")

    with gr.Tabs():
        with gr.TabItem("🔍 Global Search"):
            with gr.Row():
                q = gr.Textbox(show_label=False, placeholder="Search for research papers...", scale=4)
                search_btn = gr.Button("🔍 ANALYZE", variant="primary", scale=1)

            out_df = gr.Dataframe(headers=["Title", "Authors", "Year", "Citations"], interactive=False, wrap=True)

            with gr.Group(visible=False) as details_panel:
                sel_display = gr.Markdown()
                with gr.Row():
                    apa = gr.Textbox(label="APA Citation", show_copy_button=True)
                    mla = gr.Textbox(label="MLA Citation", show_copy_button=True)
                save_btn = gr.Button("💾 Save to Library", variant="secondary")
                save_msg = gr.Markdown()

        with gr.TabItem("📖 Personal Library"):
            lib_df = gr.Dataframe(headers=["ID", "Title", "Year"], wrap=True)
            refresh_btn = gr.Button("🔄 Refresh Library")

        with gr.TabItem("💬 Chat with Paper"):
            chat_header = gr.Markdown("### ⚠️ Select a paper from Global Search first")
            chat_input = gr.Textbox(label="Ask a specific question about the paper")
            ask_btn = gr.Button("Ask AI Researcher", variant="primary")
            chat_output = gr.Textbox(label="Llama-3.1 Analysis", lines=8, interactive=False)

    # Event Wiring
    search_btn.click(lambda query: (asyncio.run(fetch_real_data(query)), gr.update(visible=False)),
                     inputs=q, outputs=[out_df, details_panel])

    def on_select(evt: gr.SelectData, df):
        row = df.iloc[evt.index[0]]
        paper_data = row.to_dict()
        auth = row['Authors'].split(',')[0]
        return (gr.update(visible=True), f"### {row['Title']}\n\n{row['Abstract']}",
                f"{auth} et al. ({row['Year']}).", f"{auth}. \"{row['Title']}.\"",
                paper_data, f"### 💬 Analyzing: {row['Title']}")

    out_df.select(on_select, inputs=out_df,
                  outputs=[details_panel, sel_display, apa, mla, selected_paper_state, chat_header])

    save_btn.click(save_and_refresh, inputs=selected_paper_state, outputs=[save_msg, lib_df])
    refresh_btn.click(lambda: pd.read_sql_query("SELECT id, title, year FROM saved_papers", sqlite3.connect(DB_PATH)), outputs=lib_df)
    ask_btn.click(run_ai_chat, inputs=[chat_input, selected_paper_state], outputs=chat_output)

demo.launch()